import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "./globals.css";

export const metadata = {
  title: "Pickaxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
      afterSignOutUrl={"/sign-in"}
    >
      <html lang="en">
        <body style={{ fontFamily: "'Consolas', 'Monaco', monospace" }}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
