import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "./components/utilities/themeprovider";
import "./globals.css";
import Footer from "./components/utilities/footer";

export const metadata = {
  title: "Pickaxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        style={{
          fontFamily: "'Consolas', 'Monaco', monospace",
        }}
        className="bg-primary-bg-light dark:bg-primary-bg-dark"
      >
        <ThemeProvider defaultTheme="dark" storageKey="theme">
          <ClerkProvider
            appearance={{
              baseTheme: dark,
            }}
            afterSignOutUrl={"/sign-in"}
          >
            {children}
            <Footer />
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
