import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "./components/themeprovider";
import "./globals.css";

export const metadata = {
  title: "Pickaxe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body style={{ fontFamily: "'Consolas', 'Monaco', monospace" }}>
        <ThemeProvider defaultTheme="dark" storageKey="theme">
          <ClerkProvider
            appearance={{
              baseTheme: dark,
            }}
            afterSignOutUrl={"/sign-in"}
          >
            {children}
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
